apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-canary
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.12.1
    chart: istiod
    helm:
      parameters:
        - name: revisionTags
          value: 'canary'    
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
