apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.12.1
    chart: base
    helm:
      parameters:
        - name: revision
          value: 1.11.14
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
